#!/bin/bash 

az aks get-credentials --resource-group seed-resource-group --name seed-kubernetes-cluster

export AZURE_SUBSCRIPTION_ID="f2fd252d-9490-475d-a4dc-2974e02847b9"

export AZURE_LOCATION="eastus"
export AZURE_CONTROL_PLANE_MACHINE_TYPE="Standard_D2_v3"
export AZURE_NODE_MACHINE_TYPE="Standard_D4s_v3"

# Create an Azure Service Principal and paste the output here
export AZURE_TENANT_ID="201ed03f-5b3a-4b83-a14d-1e792e8861ea"
export AZURE_CLIENT_ID="7a3e84b4-05d9-4c3f-95df-b04b6c5517a9"
export AZURE_CLIENT_SECRET="xpU8Q~7H8_f6DDqsORkliz0tjYxqBYy36D5itbZU"

# Base64 encode the variables
export AZURE_SUBSCRIPTION_ID_B64="$(echo -n "$AZURE_SUBSCRIPTION_ID" | base64 | tr -d '\n')"
export AZURE_TENANT_ID_B64="$(echo -n "$AZURE_TENANT_ID" | base64 | tr -d '\n')"
export AZURE_CLIENT_ID_B64="$(echo -n "$AZURE_CLIENT_ID" | base64 | tr -d '\n')"
export AZURE_CLIENT_SECRET_B64="$(echo -n "$AZURE_CLIENT_SECRET" | base64 | tr -d '\n')"

# Settings needed for AzureClusterIdentity used by the AzureCluster
export AZURE_CLUSTER_IDENTITY_SECRET_NAME="cluster-identity-secret"
export CLUSTER_IDENTITY_NAME="cluster-identity"
export AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE="default"

# Create a secret to include the password of the Service Principal identity created in Azure
# This secret will be referenced by the AzureClusterIdentity used by the AzureCluster
kubectl create secret generic "${AZURE_CLUSTER_IDENTITY_SECRET_NAME}" --from-literal=clientSecret="${AZURE_CLIENT_SECRET}" --namespace "${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}"

# Finally, initialize the management cluster
clusterctl init --infrastructure azure

clusterctl generate cluster capi-quickstart \
  --kubernetes-version v1.25.9 \
  --control-plane-machine-count=1 \
  --worker-machine-count=1 \
  > capi-quickstart.yaml
